// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Read from environment so we can point to the audio-to-clip-maker Supabase project
const ENV_URL = (import.meta as any)?.env?.VITE_SUPABASE_URL;
const ENV_KEY = (import.meta as any)?.env?.VITE_SUPABASE_PUBLISHABLE_KEY;

// Safe fallbacks to audio-to-clip-maker project so the app never crashes blank
const FALLBACK_URL = "https://lxozpynxgvhzxxwwhklk.supabase.co";
const FALLBACK_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4b3pweW54Z3Zoenh4d3doa2xrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NjcxMjMsImV4cCI6MjA3MzM0MzEyM30.U86EvOrjuP0eFK2mPXnWFsMDkf7N0nA_8fUXb1vipV0";

const SUPABASE_URL = ENV_URL || FALLBACK_URL;
const SUPABASE_PUBLISHABLE_KEY = ENV_KEY || FALLBACK_KEY;

if (!ENV_URL || !ENV_KEY) {
  console.warn('[supabase] Using fallback Supabase project. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY to override.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
